Repository su-its/ams-backend, pull requests merged in 2021-03, with the labels that each got.

#45 github actionsの更新、およびtextlintを再帰的にmdを確認するようにした。
  .github/workflows/ci.yml
  .textlintrc
  textlint.sh
Labels: enhancement

#63 ページネーションに必要な情報が足りなかったのを修正
  app/controllers/accessLogsController.ts
  docs/OpenAPI/ams-backend-nodejs.yml
  docs/OpenAPI/redoc-static.html
Labels: do-not-merge

#66 textlintrcを技術文書寄りにしました
  .textlintrc
  docs/deployment.md
Labels: Priority:Low

#69 句点、句読点を通常の会話で使用するものに変更した
  CHANGELOG.md
  CONTRIBUTING.md
  README.md
  docs/OpenAPI/how_to_generate.md
  docs/PJ_map/AMS_API.png
  docs/PJ_map/AMS_MAP.png
  docs/PJ_map/AMS_MAP.puml
  docs/config/Redpen-config.xml
  docs/deployment.md
  package.json
Labels: documentation

#85 Github Actionsへの変更、およびReadmeの図とディレクトリの変更(図だけです)
  .github/workflows/ci.yml
  .github/workflows/eslint-review.yml
  .github/workflows/text_ci.yml
  .textlintrc
  README.md
  docs/AMS_MAP/AMS_MAP.png
  docs/AMS_MAP/AMS_MAP.puml
  docs/PJ_map/AMS_MAP.png
  docs/PJ_map/AMS_MAP.puml
  docs/config/WEB+DB_PRESS.yml
  docs/config/spellcheck.yml
  package-lock.json
  package.json
Labels: documentation
